version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - nacos-address
  nacos-address:
    image: qm012/nacos-address:latest
    restart: always
    ports:
      - 8849:8849
    depends_on:
      - redis
    links:
      - redis
    networks:
      - nacos-address
    volumes:
      - nacos-address-config:/home/nacos-address/config
      - nacos-address-logs:/home/nacos-address/logs
    environment:
      APP_MODE: standalone
      ACCOUNT_USERNAME: nacos
      ACCOUNT_PASSWORD: nacos
      REDIS_HOST: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DB: 0

volumes:
  nacos-address-config:
  nacos-address-logs:

networks:
  nacos-address: