# single machine running or not
#   standalone: standalone running
#   cluster:    cluster running (must need setting redis config)
app:
  mode: standalone

# login account: Operation API(create/delete data)
account:
  username: nacos
  password: nacos

# jwt params
jwt:
  secret: mjw2fMRc5G8LatVLdht1lbvU5qWP3NBu
  # Time unit: Hour
  expire: 4

# zap log params
zap:
  level: info
  filename: ./logs/nacos-address.log
  max_size: 200
  max_backup: 10
  max_age: 31

# redis link params,
#   cluster running,must be setting here
#   standalone running, If redis is set,it will be stored in redis,otherwise it will be stored in memory or file

#redis:
#  address: 127.0.0.1:6379
#  password: 123456
#  db: 0